# Generated by Django 4.0.6 on 2022-07-05 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
